window.GT_DATA = (() => {
  const curriculum = [
    {w:1,title:"Seviye tespiti + temel boşluklar",goal:"Mevcut İspanyolcayı ölç, vatandaşlık kelimelerine giriş yap.",tasks:["Busuu Placement Test sonucunu kaydet","Ser/estar + presente hızlı tekrar","20 temel naturalización kelimesi","Guatemala'nın 22 departamento yapısını öğren","2 kısa kendini tanıtma kaydı"]},
    {w:2,title:"Geçmişini anlat",goal:"Guatemala'daki yaşamını ve aile bağını rahat anlat.",tasks:["Pretérito perfecto / indefinido tekrar","2010–2014 Guatemala geçmişini 90 sn anlat","Evlilik ve aile kelime seti","10 civics sorusu x 3","Drops 5 gün x 5–10 dk"]},
    {w:3,title:"İdari İspanyolca",goal:"Belge, randevu, başvuru ve resmi soru diline alış.",tasks:["Solicitud / expediente / trámite kelimeleri","Por/para ve resmi bağlaçlar","Bir başvuru durumunu sorma diyaloğu","Anayasa: Estado ve temel ilkeler","Busuu 60+ dakika"]},
    {w:4,title:"Guatemala coğrafyası",goal:"Ülkenin temel bölgesel yapısını öğren.",tasks:["22 departamento tekrarları","Komşu ülkeler + temel coğrafya","Yer-yön ve seyahat dili","20 soruluk coğrafya denemesi","5 dk serbest konuşma"]},
    {w:5,title:"Guatemala tarihi I",goal:"Bağımsızlık ve temel tarih çizgisini kur.",tasks:["15 Eylül 1821 ve bağımsızlık bağlamı","Maya mirası temel kavramları","Tarih anlatırken geçmiş zaman","Civics accuracy ≥ %75","Busuu grammar review"]},
    {w:6,title:"Anayasa ve haklar",goal:"Anayasanın temel yapısını sade İspanyolcayla açıklayabil.",tasks:["Constitución: temel ilkeler","Derechos / deberes kelime seti","3 devlet organını açıkla","15 dakikalık mock civics","Zayıf kelimeleri %70 azalt"]},
    {w:7,title:"Devlet yapısı",goal:"Ejecutivo, Legislativo, Judicial ayrımını kavra.",tasks:["Üç organın temel işlevleri","Congreso ve anayasal yapı","Kurumsal kelime kartları","Sözlü 10 soru-cevap","Drops review ağırlıklı"]},
    {w:8,title:"Akıcılık haftası",goal:"Doğru fakat yavaş İspanyolcadan doğal akışa geç.",tasks:["Her gün 3 dk sesli monolog","Bağlaçlar: además, sin embargo, por eso","Busuu Conversations / speaking","Kendi 10 hatanı kelime bankasına ekle","Civics accuracy ≥ %80"]},
    {w:9,title:"Mülakat simülasyonu I",goal:"Kişisel dosyanla ilgili sorulara hazırlıklı ol.",tasks:["Por qué quiere naturalizarse?","Guatemala ile bağların","Aile ve ikamet geçmişi","5 soruluk ses kaydı","Cevapları 60–120 sn aralığına getir"]},
    {w:10,title:"Zayıf alan temizliği",goal:"Veriye göre düşük kalan alanlara yüklen.",tasks:["En düşük beceriyi seç","50 SRS tekrar","2 x 20 soruluk civics","Busuu weak vocabulary review","Bir tam konuşma mock'u"]},
    {w:11,title:"Mülakat simülasyonu II",goal:"Baskı altında kısa, net ve tutarlı cevap ver.",tasks:["Rastgele 15 sözlü soru","30 soruluk civics denemesi","Belge / işlem rol oyunu","B2 bağlaçlarını aktive et","Toplam 150+ dk haftalık çalışma"]},
    {w:12,title:"Final hazırlık",goal:"Sınav varmış gibi tam prova yap.",tasks:["İspanyolca 15 dk sözlü prova","40 soruluk civics prova","Zayıf kelimelerde son tur","Kendi dosyanı 2 dk anlat","Sonuçları kaydet ve bakım planı oluştur"]}
  ];

  const vocab = [
    ["la naturalización","vatandaşlığa kabul / naturalizasyon","La naturalización es el proceso para adquirir una nacionalidad."],
    ["la ciudadanía","vatandaşlık","La ciudadanía implica derechos y deberes."],
    ["la nacionalidad","uyruk / milliyet","Deseo adquirir la nacionalidad guatemalteca."],
    ["la solicitud","başvuru / dilekçe","Presenté la solicitud con todos los documentos."],
    ["el expediente","dosya","Mi expediente está completo."],
    ["el trámite","resmî işlem / süreç","Quiero conocer el estado de mi trámite."],
    ["el requisito","şart / gereklilik","¿Cuáles son los requisitos del procedimiento?"],
    ["el documento","belge","Necesito presentar este documento en original."],
    ["la certificación","tasdik / sertifika","La certificación debe estar vigente."],
    ["la constancia","belge / kayıt kanıtı","Solicité una constancia de residencia."],
    ["el antecedente","geçmiş kayıt","Me pidieron antecedentes para el expediente."],
    ["la residencia","ikamet","Tuve residencia permanente en Guatemala."],
    ["residir","ikamet etmek","Residí en Guatemala durante varios años."],
    ["el domicilio","yerleşim adresi","Mi domicilio estaba en la Ciudad de Guatemala."],
    ["el vínculo","bağ","Mantengo un vínculo familiar con Guatemala."],
    ["el cónyuge","eş","Mi cónyuge es ciudadana guatemalteca."],
    ["contraer matrimonio","evlenmek","Contrajimos matrimonio en 2011."],
    ["el matrimonio","evlilik","Nuestro matrimonio continúa vigente."],
    ["el parentesco","akrabalık bağı","El parentesco se acredita con documentos."],
    ["el acta","resmî tutanak / belge","Presenté el acta correspondiente."],
    ["la partida de nacimiento","doğum kayıt belgesi","Necesito una partida de nacimiento reciente."],
    ["la autoridad","yetkili makam","La autoridad revisará el expediente."],
    ["la gobernación","valilik / departman yönetimi","La gobernación participa en ciertos trámites."],
    ["el ministerio","bakanlık","El ministerio analiza la documentación."],
    ["la ley","kanun","La ley establece los requisitos."],
    ["la Constitución","Anayasa","La Constitución es la ley suprema del país."],
    ["el derecho","hak / hukuk","La Constitución reconoce derechos fundamentales."],
    ["el deber","ödev / yükümlülük","Los ciudadanos también tienen deberes."],
    ["la libertad","özgürlük","La libertad es un principio constitucional."],
    ["la igualdad","eşitlik","La igualdad ante la ley es fundamental."],
    ["la justicia","adalet","El Estado debe garantizar la justicia."],
    ["la seguridad","güvenlik","La seguridad es uno de los deberes del Estado."],
    ["la paz","barış","La Constitución menciona la paz y el desarrollo integral."],
    ["el bien común","kamu yararı / ortak iyilik","El bien común es un fin supremo del Estado."],
    ["el Estado","devlet","Guatemala es un Estado libre, independiente y soberano."],
    ["el gobierno","hükümet / yönetim","El sistema de gobierno es republicano, democrático y representativo."],
    ["el Organismo Ejecutivo","Yürütme organı","El Organismo Ejecutivo forma parte de la estructura del Estado."],
    ["el Organismo Legislativo","Yasama organı","El Congreso integra el Organismo Legislativo."],
    ["el Organismo Judicial","Yargı organı","El Organismo Judicial ejerce la función jurisdiccional."],
    ["el Congreso","Kongre","El Congreso ejerce la función legislativa."],
    ["la soberanía","egemenlik","La soberanía corresponde al pueblo."],
    ["independiente","bağımsız","Guatemala es un Estado independiente."],
    ["soberano","egemen","La Constitución define al país como soberano."],
    ["representativo","temsili","El gobierno guatemalteco es representativo."],
    ["democrático","demokratik","El sistema de gobierno es democrático."],
    ["republicano","cumhuriyetçi / cumhuriyet esaslı","El sistema de gobierno es republicano."],
    ["el departamento","departman / il düzeyi idari birim","Guatemala tiene 22 departamentos."],
    ["la cabecera","idari merkez","Cada departamento tiene una cabecera departamental."],
    ["la frontera","sınır","Guatemala comparte fronteras con varios países."],
    ["la independencia","bağımsızlık","La independencia centroamericana se proclamó en 1821."],
    ["la historia","tarih","Estudio la historia elemental de Guatemala."],
    ["la geografía","coğrafya","La prueba puede incluir geografía elemental."],
    ["comprender","anlamak","Puedo comprender preguntas en español."],
    ["explicar","açıklamak","Puedo explicar mi vínculo con Guatemala."],
    ["acreditar","kanıtlamak / belgelendirmek","Debo acreditar ciertos hechos con documentos."],
    ["presentar","sunmak","Voy a presentar la documentación requerida."],
    ["adjuntar","eklemek","Adjunté una copia al expediente."],
    ["firmar","imzalamak","Debo firmar la solicitud."],
    ["comparecer","makam önüne çıkmak","Puede ser necesario comparecer personalmente."],
    ["declarar","beyan etmek","Declaré la información de forma clara."],
    ["vigente","yürürlükte / geçerli","El documento debe estar vigente."],
    ["cumplir","yerine getirmek","Quiero cumplir todos los requisitos."],
    ["aprobar","geçmek / onaylamak","Mi objetivo es aprobar la evaluación."],
    ["mejorar","geliştirmek","Necesito mejorar mi expresión oral."],
    ["la entrevista","mülakat","Estoy preparándome para una entrevista."],
    ["la evaluación","değerlendirme / sınav","La evaluación de español es práctica."],
    ["la instrucción cívica","yurttaşlık bilgisi","También estudio instrucción cívica."],
    ["por lo tanto","bu nedenle","Viví varios años en Guatemala; por lo tanto, conozco bien el país."],
    ["sin embargo","ancak / bununla birlikte","Vivo fuera del país; sin embargo, mantengo fuertes vínculos familiares."],
    ["además","ayrıca","Además, mis hijas son ciudadanas guatemaltecas."],
    ["desde entonces","o zamandan beri","Nos casamos en 2011 y seguimos casados desde entonces."],
    ["durante","boyunca","Viví en Guatemala durante cuatro años."],
    ["actualmente","şu anda","Actualmente vivo en Georgia."],
    ["anteriormente","daha önce","Anteriormente trabajé en Guatemala."],
    ["mantener","sürdürmek / korumak","Mantengo vínculos personales y familiares con Guatemala."],
    ["pertenecer","ait olmak","Mi familia pertenece a dos culturas."],
    ["conocer","bilmek / tanımak","Conozco aspectos básicos de la Constitución."],
    ["recordar","hatırlamak","Necesito recordar estas fechas importantes."],
    ["responder","cevaplamak","Puedo responder preguntas con claridad."]
  ].map((x,i)=>({id:`v${i+1}`,es:x[0],tr:x[1],ex:x[2],tags:i<24?["admin"]:i<47?["civics"]:["language"]}));

  const civics = [
    {id:"c1",topic:"Constitución",q:"¿Cuál es la ley suprema de Guatemala?",a:["El Código Civil","La Constitución Política de la República","La Ley Electoral","El Código Municipal"],correct:1,e:"La Constitución Política de la República es la norma suprema del Estado."},
    {id:"c2",topic:"Constitución",q:"¿En qué año fue emitida la actual Constitución Política de Guatemala?",a:["1965","1985","1993","2001"],correct:1,e:"Fue emitida el 31 de mayo de 1985 y entró en vigencia en enero de 1986."},
    {id:"c3",topic:"Constitución",q:"Según la Constitución, ¿cuál es el fin supremo del Estado de Guatemala?",a:["La expansión territorial","La realización del bien común","El crecimiento de las exportaciones","La centralización administrativa"],correct:1,e:"El artículo 1 establece que el fin supremo es la realización del bien común."},
    {id:"c4",topic:"Constitución",q:"¿Cuál de estos aparece entre los deberes del Estado en el artículo 2?",a:["Garantizar la vida, la libertad, la justicia, la seguridad y la paz","Garantizar empleo público a todos","Fijar un único idioma doméstico","Eliminar los gobiernos municipales"],correct:0,e:"El artículo 2 enumera vida, libertad, justicia, seguridad, paz y desarrollo integral de la persona."},
    {id:"c5",topic:"Estado",q:"¿Cómo describe la Constitución el sistema de gobierno de Guatemala?",a:["Monárquico y federal","Republicano, democrático y representativo","Parlamentario y unitario","Confederal y directo"],correct:1,e:"La Constitución describe el sistema como republicano, democrático y representativo."},
    {id:"c6",topic:"Estado",q:"¿Cuáles son los tres organismos fundamentales del Estado?",a:["Ejecutivo, Legislativo y Judicial","Municipal, Electoral y Militar","Fiscal, Bancario y Municipal","Nacional, Regional y Provincial"],correct:0,e:"La estructura estatal distingue los organismos Ejecutivo, Legislativo y Judicial."},
    {id:"c7",topic:"Estado",q:"¿Qué organismo está relacionado con el Congreso de la República?",a:["Organismo Judicial","Organismo Legislativo","Organismo Ejecutivo","Ministerio Público"],correct:1,e:"El Congreso constituye el órgano legislativo unicameral de Guatemala."},
    {id:"c8",topic:"Estado",q:"¿Qué función general corresponde al Organismo Judicial?",a:["Aprobar el presupuesto familiar","Ejercer la función jurisdiccional","Dirigir todos los municipios","Emitir moneda"],correct:1,e:"El Organismo Judicial ejerce la función jurisdiccional conforme al orden constitucional."},
    {id:"c9",topic:"Geografía",q:"¿Cuántos departamentos tiene Guatemala?",a:["18","20","22","24"],correct:2,e:"Guatemala se divide administrativamente en 22 departamentos."},
    {id:"c10",topic:"Geografía",q:"¿Cuál es la capital de Guatemala?",a:["Antigua Guatemala","Quetzaltenango","Ciudad de Guatemala","Escuintla"],correct:2,e:"La capital nacional es la Ciudad de Guatemala."},
    {id:"c11",topic:"Geografía",q:"¿Cuál de estos es un departamento de Guatemala?",a:["Petén","Yucatán","Chiapas","Copán"],correct:0,e:"Petén es uno de los 22 departamentos de Guatemala."},
    {id:"c12",topic:"Geografía",q:"¿Cuál de estos NO es un departamento de Guatemala?",a:["Alta Verapaz","Sacatepéquez","Belice","Jalapa"],correct:2,e:"Belice es un país vecino, no un departamento guatemalteco."},
    {id:"c13",topic:"Historia",q:"¿Qué fecha aparece asociada a la independencia de Centroamérica y en el escudo de Guatemala?",a:["15 de septiembre de 1821","20 de octubre de 1944","31 de mayo de 1985","14 de enero de 1986"],correct:0,e:"El 15 de septiembre de 1821 es la fecha de la independencia centroamericana y figura en el escudo."},
    {id:"c14",topic:"Historia",q:"¿Qué civilización prehispánica tiene una presencia histórica central en Guatemala?",a:["Romana","Maya","Vikinga","Persa"],correct:1,e:"La civilización maya es fundamental en la historia y patrimonio cultural de Guatemala."},
    {id:"c15",topic:"Constitución",q:"¿Cuántos artículos tiene la Constitución Política de la República de Guatemala?",a:["181","220","281","350"],correct:2,e:"El Congreso de Guatemala indica que la Constitución está conformada por 281 artículos."},
    {id:"c16",topic:"Constitución",q:"¿Qué parte de la Constitución reúne principalmente derechos y garantías fundamentales?",a:["La parte dogmática","La parte presupuestaria","La parte municipal","La parte aduanera"],correct:0,e:"La sección dogmática contiene los derechos y garantías fundamentales."},
    {id:"c17",topic:"Constitución",q:"¿Qué parte constitucional organiza la estructura y funciones del Estado?",a:["Dogmática","Orgánica","Geográfica","Tributaria"],correct:1,e:"La sección orgánica regula la organización del Estado y sus instituciones."},
    {id:"c18",topic:"Derechos",q:"¿Qué principio reconoce el artículo 4 de la Constitución?",a:["Libertad e igualdad","Servicio militar obligatorio universal","Monopolio estatal del comercio","Ciudadanía automática para visitantes"],correct:0,e:"El artículo 4 reconoce libertad e igualdad en dignidad y derechos."},
    {id:"c19",topic:"Derechos",q:"¿Cuál de estos conceptos está directamente vinculado con el artículo 12 de la Constitución?",a:["Derecho de defensa","Derecho de importación","Derecho de navegación","Derecho de patentes"],correct:0,e:"El artículo 12 protege el derecho de defensa y el debido proceso."},
    {id:"c20",topic:"Estado",q:"Guatemala se define constitucionalmente como un Estado…",a:["Libre, independiente y soberano","Dependiente y confederal","Monárquico y colonial","Federal y hereditario"],correct:0,e:"La Constitución define a Guatemala como Estado libre, independiente y soberano."},
    {id:"c21",topic:"Geografía",q:"¿Cuál de estos departamentos se encuentra en Guatemala?",a:["Quetzaltenango","Oaxaca","Cortés","Santa Ana"],correct:0,e:"Quetzaltenango es departamento guatemalteco."},
    {id:"c22",topic:"Geografía",q:"¿Cuál de estos departamentos forma parte de Guatemala?",a:["Huehuetenango","Cayo","Sonsonate","Francisco Morazán"],correct:0,e:"Huehuetenango es uno de los departamentos de Guatemala."},
    {id:"c23",topic:"Geografía",q:"¿Cuál de estos departamentos guatemaltecos está en el norte y tiene gran extensión territorial?",a:["Petén","Jutiapa","Sacatepéquez","Totonicapán"],correct:0,e:"Petén ocupa una extensa zona del norte de Guatemala."},
    {id:"c24",topic:"Historia",q:"¿En qué fecha fue emitida la actual Constitución?",a:["31 de mayo de 1985","15 de septiembre de 1821","29 de diciembre de 1996","20 de octubre de 1944"],correct:0,e:"La Constitución actual fue emitida el 31 de mayo de 1985."},
    {id:"c25",topic:"Historia",q:"¿Cuándo entró en vigencia la Constitución emitida en 1985?",a:["14 de enero de 1986","1 de enero de 1985","15 de septiembre de 1985","31 de mayo de 1993"],correct:0,e:"Entró en vigencia el 14 de enero de 1986."},
    {id:"c26",topic:"Estado",q:"¿El Congreso de Guatemala es unicameral o bicameral?",a:["Unicameral","Bicameral","Tricameral","No tiene cámaras legislativas"],correct:0,e:"El Congreso de la República es un órgano legislativo unicameral."},
    {id:"c27",topic:"Derechos",q:"¿Qué valor constitucional se relaciona con que las personas sean libres e iguales en dignidad y derechos?",a:["Igualdad","Herencia","Centralización","Exclusividad"],correct:0,e:"La igualdad es uno de los principios expresamente reconocidos."},
    {id:"c28",topic:"Constitución",q:"¿Qué instrumento protege el orden constitucional y los derechos frente a ciertas vulneraciones?",a:["El amparo","La factura","La patente comercial","El arancel"],correct:0,e:"El amparo es una garantía constitucional de protección."},
    {id:"c29",topic:"Geografía",q:"¿Cuál de estos es un departamento de la región central del país?",a:["Guatemala","Texas","Cortés","Cayo"],correct:0,e:"Guatemala es tanto el nombre del país como de uno de sus departamentos."},
    {id:"c30",topic:"Estado",q:"¿Qué palabra describe mejor un sistema en el que las autoridades son elegidas y existe representación política?",a:["Representativo","Hereditario","Colonial","Feudal"],correct:0,e:"La Constitución caracteriza el gobierno como republicano, democrático y representativo."}
  ];

  const speaking = [
    {q:"¿Por qué desea adquirir la nacionalidad guatemalteca?",hint:"Motivación + vínculo familiar + historia personal con Guatemala."},
    {q:"¿Cuánto tiempo vivió en Guatemala y qué hacía allí?",hint:"Fechas aproximadas, trabajo, vida cotidiana."},
    {q:"¿Cuándo contrajo matrimonio y cómo mantiene su vínculo con Guatemala?",hint:"Matrimonio, familia y continuidad del vínculo."},
    {q:"¿Qué significa Guatemala para usted y su familia?",hint:"Respuesta personal, concreta y breve."},
    {q:"¿Qué conoce sobre la Constitución de Guatemala?",hint:"Ley suprema + derechos + organización del Estado."},
    {q:"¿Cuáles son los tres organismos del Estado de Guatemala?",hint:"Ejecutivo, Legislativo, Judicial + una frase de función general."},
    {q:"¿Cómo explicaría el concepto de bien común?",hint:"Interés general / bienestar de la población."},
    {q:"¿Qué documentos cree que son importantes en un trámite de naturalización?",hint:"No inventes requisitos: habla en general de identificación, estado civil, antecedentes, residencia, etc."},
    {q:"¿Qué haría si una autoridad le pide aclarar un dato de su expediente?",hint:"Comprender, pedir precisión, responder y aportar documentación."},
    {q:"Cuéntenos brevemente su historia personal con Guatemala.",hint:"Máximo 2 minutos: llegada, trabajo, matrimonio, familia, salida y vínculo actual."},
    {q:"¿Por qué está mejorando su español ahora?",hint:"Capacidad de participar plenamente en trámites y vida cívica."},
    {q:"¿Qué aspectos de la historia y geografía de Guatemala conoce?",hint:"Da 2–3 ejemplos seguros, no intentes impresionar con datos inciertos."}
  ];

  return {curriculum,vocab,civics,speaking};
})();